Bootstrap: docker
From: nvidia/cuda:10.0-devel

%setup
mkdir ${SINGULARITY_ROOTFS}/workspace

%files
%labels
    Pytorch environment
    Build with:
    sudo singularity build --writable dtorch.img dtorch.txt
    singularity exec --nv dtorch.img python


%post
mkdir /project /scratch

#Now install everythin
apt-get update && apt-get -y install wget

DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3 \
        python3-tk \
        python3-pip \
        python3-dev
rm -rf /var/lib/apt/lists/*
pip3 install pipenv \
torch>=1.0.0 \
torchvision \
dominate>=2.3.1 \
dill \
scikit-image \
numpy>=1.15.4 \
scipy>=1.1.0 \
matplotlib==3.0.2 \
opencv-python>=3.4.3.18 \ 
tensorboard==1.14.0 \
face-alignment==1.0.0 \

cd /workspace

%environment


%runscript
